language: python
python:
  - "3.5.1"
install:
  - pip install -r requirements.txt
  - pip install -r nuremberg/core/tests/requirements.txt
services:
  - mysql
before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS test_nuremberg_dev'
  - mysql -uroot -e 'CREATE USER nuremberg; GRANT ALL ON test_nuremberg_dev.* TO nuremberg'
  - mysql -unuremberg test_nuremberg_dev < nuremberg/core/tests/data.sql
script: py.test
