language: python
python:
  - "3.5.1"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y node-less yui-compressor
install:
  - pip install -r requirements.txt
  - pip install -r nuremberg/core/tests/requirements.txt
services:
  - mysql
before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS test_nuremberg_dev'
  - mysql -uroot -e 'CREATE USER nuremberg; GRANT ALL ON test_nuremberg_dev.* TO nuremberg'
  - mysql -unuremberg test_nuremberg_dev < nuremberg/core/tests/data.sql
  - curl -sSO http://archive.apache.org/dist/lucene/solr/4.10.3/solr-4.10.3.tgz
  - curl -sSL https://raw.githubusercontent.com/ksclarke/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.10.3 SOLR_CONFS="schema.xml" bash
script: py.test
